FROM node:22-alpine

WORKDIR /workspace

COPY package.json package-lock.json ./
COPY apps/server/package.json ./apps/server/package.json
COPY apps/client/package.json ./apps/client/package.json
COPY apps/keycloak-theme/package.json ./apps/keycloak-theme/package.json

RUN npm ci

COPY . .

WORKDIR /workspace/apps/server

CMD ["npm", "run", "start:worker"]

